### ISSUE TITLE
Party mode 

### ISSUE THREAD

**Issue by evil-morfar** [Ladekarl/kollegianer#2]
Det lader til at party mode knappen godt nok aktiverer lyset, men den sender en tom tekst streng til firebase, sådan så knappen ikke bliver grøn.

**Comment by Ladekarl** [comment]
Jeg kunne forestille mig fejlen kommer fordi app'en er blevet omgået. Hvis man tænder/slukker udenfor app'en, så kan man vende rundt på hvad der er tændt og slukket på app'en. Så vidt jeg husker tændte Joakim lyset udenfor app'en på et tidspunkt.

**Comment by evil-morfar** [comment]
Lyder plausibelt nok. Ville bare lige nævne det.

**Comment by Ladekarl** [comment]
Et hurtigt fix er at omgå app'en en gang til så man får den rigtige rækkefølge.
Nu kan jeg ikke huske hvad man får af svar tilbage, men kan man få status ud af responsen?

**Comment by evil-morfar** [comment]
Ja, der bliver sendt et http svar (200?) med enten 1 eller 0. Men det er lige meget, da den specifikke on/off adresse bliver kaldt.

**Comment by evil-morfar** [comment]
Okay, har lige tjekket, og det har ikke noget med det at gøre. Den eneste forklaring er, at `localUser` somehow er tom i https://github.com/Ladekarl/kollegianer/blob/master/src/components/Overview.js#L284

**Comment by evil-morfar** [comment]
I øvrigt har jeg skiftet telefon og kører nu android 9 - det kunne også have betydning.

**Comment by Ladekarl** [comment]
Det kan godt være. Jeg prøver lige at Release den nye version. Har opdateret alle libraries inklusive React Native og Firebase.
